
project: ballerina_getting_started

# Set this if you want to carry over parent process' environment variables
# carry_env: true 
carry_env: true

#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:

#
# Providers
#
providers:
  dotenv:
    env_sync:
      path: .env